# -*- coding: utf-8 -*-
"""EnergIA_Grupo33_graphs.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkDgmnCgZbJYUuSS5cLt-vB4LCc5GebI

# Análisis Inteligente del Consumo Energético

El objetivo de este proyecto es desarrollar un modelo de Machine Learning capaz de clasificar el nivel de eficiencia energética de una vivienda o pequeño establecimiento a partir de diferentes características relacionadas con el consumo eléctrico.

Se generará un dataset sintético que represente distintos perfiles de consumo.

Posteriormente se realizará un análisis exploratorio de los datos (EDA), el entrenamiento de modelos supervisados y la evaluación de su desempeño para seleccionar el modelo más adecuado.

# Variables del Dataset

Para representar el comportamiento energético de una vivienda se seleccionaron las siguientes variables.

1. Fecha

      Tipo: Fecha (YYYY-MM)

      -Representa el período al que corresponde el consumo energético registrado.

      Permite realizar análisis temporales como:

      -Evolución del consumo.

      -Comparación entre meses.

      -Tendencias de eficiencia.

      -Variaciones estacionales.

2. Consumo mensual (kWh)

      Tipo: Numérica

      Representa la cantidad de energía consumida durante un mes.

      Es la variable principal del problema y será utilizada para:

      -Estimar el costo mensual.

      -Analizar patrones de consumo.

      -Detectar consumos elevados.
      
3. Uso en horario pico

      Tipo: Booleana

      Indica si la mayor parte del consumo ocurre durante los horarios de mayor demanda eléctrica.

      Su análisis permite:

      -Detectar hábitos poco eficientes.

      -Generar recomendaciones para redistribuir el consumo.

4. Horas de alto consumo

      Tipo: Numérica

      Cantidad aproximada de horas diarias durante las cuales el consumo eléctrico es elevado.

      Permite identificar:

      -Intensidad del uso energético.

      -Relación entre tiempo de uso y consumo mensual.

5. Cantidad de equipos eléctricos

      Tipo: Numérica

      Número de electrodomésticos o equipos eléctricos utilizados regularmente.

      -Esta variable permite analizar cómo influye la cantidad de dispositivos sobre el consumo energético.

6. Cantidad de personas

      Tipo: Numérica

      -Cantidad de personas que habitan el inmueble.

      Se incorpora debido a que el consumo suele aumentar con el número de habitantes.

7. Tipo de inmueble

      Tipo: Categórica

      Puede tomar los valores:

      -Casa

      -Departamento

      -Comercio

      Permite analizar diferencias de consumo entre distintos tipos de establecimientos.

8. Categoría de eficiencia energética (Target)

      Tipo: Categórica

      Representa la clasificación que el modelo deberá aprender.

      Se utilizarán tres categorías:

      -Eficiente

      -Moderado
      
      -Ineficiente

      Las etiquetas serán generadas mediante un conjunto de reglas que consideran el consumo energético y otros factores relacionados con los hábitos de uso.

# Generación del Dataset

Se desarrolló un generador de datos sintéticos.

El objetivo es representar distintos perfiles de consumo energético manteniendo relaciones coherentes entre las variables.

Se generarán 1000 registros correspondientes a distintos inmuebles con características variadas.

Posteriormente estas observaciones serán utilizadas para entrenar y evaluar modelos supervisados de clasificación.
"""

import random
import pandas as pd
from datetime import datetime

# AB_sugerencia -> ¿aquí podríamos insertar random.seed(42)?
random.seed(42)

NUM_REGISTROS = 1000

TIPOS_INMUEBLE = [
    "Casa",
    "Departamento",
    "Comercio"
]
def generar_fecha():
    año = random.randint(2023, 2025)
    mes = random.randint(1, 12)
    return datetime(año, mes, 1).strftime("%Y-%m")


def generar_tipo():
    return random.choices(
        TIPOS_INMUEBLE,
        weights=[50, 35, 15]
    )[0]


def generar_personas(tipo):

    if tipo == "Casa":
        return random.randint(2, 6)

    elif tipo == "Departamento":
        return random.randint(1, 4)

    return random.randint(2, 8)


def generar_equipos(personas):
    return random.randint(personas + 2, personas + 10)


def generar_horas(): #AB_sugerencia: ¿se podría escribir así: def generar_horas_alto_consumo():?
    return random.randint(2, 12)


def generar_horario_pico():
    return random.random() < 0.65


def calcular_consumo(personas, equipos, horas, horario_pico):

    consumo = 80

    consumo += personas * random.randint(20, 35)

    consumo += equipos * random.randint(6, 10)

    consumo += horas * random.randint(8, 15) #AB_sugerencia ->  ¿se podría escribir horas_alto_consumo en lugar de horas?

    if horario_pico:
        consumo += random.randint(20, 50)

    consumo += random.randint(-15, 15)

    return max(consumo, 100)

#Indice para calcular categoria

def calcular_indice(consumo,
                    horario_pico,
                    horas,
                    equipos,
                    personas):

    indice = 100

    if consumo > 600:
        indice -= 40
    elif consumo > 450:
        indice -= 25
    elif consumo > 300:
        indice -= 10

    if horario_pico:
        indice -= 15

    if horas >= 10:
        indice -= 15
    elif horas >= 7:
        indice -= 8


    if equipos >= 15:
        indice -= 15
    elif equipos >= 10:
        indice -= 8


    if personas >= 5:
        indice -= 5

    indice += random.randint(-8, 8)

    indice = max(0, min(indice, 100))

    return indice

def clasificar(indice):

    if indice >= 75:
        return "Eficiente"

    elif indice >= 45:
        return "Moderado"

    return "Ineficiente"


def generar_registro():

    tipo = generar_tipo()

    personas = generar_personas(tipo)

    equipos = generar_equipos(personas)

    horas = generar_horas() #AB_sugerencia -> ¿se puede escribir aquí horas_alto_consumo = generar_horas_alto_consumo()?

    horario_pico = generar_horario_pico()

    consumo = calcular_consumo(
        personas,
        equipos,
        horas,
        horario_pico
    )

    indice = calcular_indice(
        consumo,
        horario_pico,
        horas,
        equipos,
        personas
    )

    categoria = clasificar(indice)

    return {
        "fecha": generar_fecha(),
        "consumo_kwh": consumo,
        "uso_horario_pico": horario_pico,
        "horas_alto_consumo": horas,
        "cantidad_equipos": equipos,
        "cantidad_personas": personas,
        "tipo_inmueble": tipo,
        "categoria": categoria
    }

dataset = []

for _ in range(NUM_REGISTROS):
    dataset.append(generar_registro())

df = pd.DataFrame(dataset)

df.to_csv(
    "consumo_energetico.csv",
    index=False,
    encoding="utf-8"
)

print(df.head())

print("\nDistribución de categorías:")
print(df["categoria"].value_counts())

"""#Conociendo el Data Set"""

import pandas as pd
import numpy as np
df = pd.read_csv("consumo_energetico.csv")

print("Primeros registros")
df.head()

print("Últimos registros")
df.tail()

print(f"Filas: {df.shape[0]}")
print(f"Columnas: {df.shape[1]}")

df.info()

df.describe()

print("Consumo promedio")

df["consumo_kwh"].mean()

print("Consumo mínimo")
print(df["consumo_kwh"].min())

print("Consumo máximo")
print(df["consumo_kwh"].max())

TARIFA = 0.75

df["costo_estimado"] = df["consumo_kwh"] * TARIFA

print("Costo promedio mensual")

df["costo_estimado"].mean()

df["costo_estimado"].describe()

df["categoria"].value_counts()

round(
    df["categoria"].value_counts(normalize=True)*100,
    2
)

df["tipo_inmueble"].value_counts()

round(
    df["tipo_inmueble"].value_counts(normalize=True)*100,
    2
)

df["uso_horario_pico"].value_counts()

round(
    df["uso_horario_pico"].value_counts(normalize=True)*100,
    2
)

df.groupby("tipo_inmueble")["consumo_kwh"].mean().sort_values(ascending=False)

df.groupby("categoria")["consumo_kwh"].mean()

"""#Gráficos

### VISUALIZACIÓN Y ANÁLISIS DEL CONSUMO ENERGÉTICO
•    Se implementó Seaborn y Matplotlib para generar visualizaciones del consumo energético.

•    Se analizó la relación entre categoría de eficiencia energética, consumo, costo y tipo de inmueble.


Objetivo:

Identificar patrones, diferencias y relaciones que permitan interpretar el comportamiento energético del tipo de inmueble y apoyar la toma de decisiones.


Gráficos generados:

•    📊 Distribución de categoría de eficiencia energética.

•    💰 Costo promedio por categoría y tipo de inmueble.

•    🔵 Relación entre equipos, horas de alto consumo y consumo energético.

•    📈 Distribución del consumo energético mediante histograma.

•    🔥 Heatmap del costo promedio por tipo de inmueble y categoría de eficiencia energética.

•    🔗 Matriz de correlación entre variables.
"""

import matplotlib.pyplot as plt
import matplotlib.image as mpimg
import seaborn as sns
from IPython.display import display, HTML

# ======================
# CONFIGURACIÓN GENERAL
# ======================

sns.set_theme(style="whitegrid")

# =================
# COLORES LEAF WATT
# =================

# Colores inspirados directamente en el logo
COLOR_VERDE_OSCURO = "#1C493B"
COLOR_VERDE_PROFUNDO = "#084331"
COLOR_VERDE_LIMA = "#9AD348"
COLOR_VERDE_MEDIO = "#5E9F45"
COLOR_AMARILLO_PASTEL = "#F3D98B"
COLOR_GRIS_LOGO = "#44494C"

COLOR_HISTOGRAMA = COLOR_VERDE_MEDIO

# Escala de colores para los Heatmaps
COLOR_CMAP_COSTO = "YlGn"
COLOR_CMAP_CORRELACION = "RdYlGn"

COLOR_BORDE = "black"
ANCHO_BORDE = 1

# ======================
# CONFIGURACIÓN DEL LOGO
# ======================

RUTA_LOGO = "/content/Logo LW(collab).png"

# ==========================================
# FUNCIÓN PARA AGREGAR EL LOGO AL GRÁFICO
# ==========================================

def agregar_logo(fig, ruta_logo):
    """
    Se coloca el logo de Leaf Watt fuera del área
    principal del gráfico, en la parte superior derecha.
    """

    logo = mpimg.imread(ruta_logo)

    # Crear un área exclusiva para el logo
    ax_logo = fig.add_axes([0.90, 0.86, 0.12, 0.15])

    ax_logo.imshow(logo)
    ax_logo.axis("off")

# =============
# CREAR PALETAS
# =============

def crear_paleta_categoria(df):
    """
    Se crea una paleta consistente para las categorías.
    Los mismos colores se mantienen en todos
    los gráficos donde aparecen las categorías.
    """

    categorias = df["categoria"].value_counts().index

    # Colores fijos para cada categoría
    colores_categoria = {
        "Eficiente": COLOR_VERDE_LIMA,
        "Moderado": COLOR_AMARILLO_PASTEL,
        "Ineficiente": COLOR_GRIS_LOGO
    }

    paleta_categoria = {
        categoria: colores_categoria[categoria]
        for categoria in categorias
    }

    return categorias, paleta_categoria

def crear_paleta_tipo(df):
    """
    Se crea una paleta consistente para los tipos de inmueble.
    Los mismos colores se mantienen en todos
    los gráficos donde aparecen los tipos.
    """

    tipos = df["tipo_inmueble"].value_counts().index

    # Colores fijos para cada tipo
    colores_tipo = {
        "Departamento": COLOR_VERDE_OSCURO,
        "Casa": COLOR_VERDE_MEDIO,
        "Comercio": COLOR_AMARILLO_PASTEL
    }

    paleta_tipo = {
        tipo: colores_tipo[tipo]
        for tipo in tipos
    }

    return tipos, paleta_tipo

# ===============
# FORMATO GENERAL
# ===============

def formato(ax, titulo, xlabel="", ylabel="", leyenda=False, rotacion_x=0, subtitulo=""):
    """
    Aplica el mismo formato a cualquier gráfico.
    """

    # Mostrar borde en TODOS los gráficos
    for spine in ax.spines.values():
        spine.set_visible(True)
        spine.set_edgecolor(COLOR_BORDE)
        spine.set_linewidth(ANCHO_BORDE)

    # Borde de la leyenda
    if leyenda and ax.get_legend() is not None:
        ax.get_legend().get_frame().set_edgecolor(COLOR_BORDE)
        ax.get_legend().get_frame().set_linewidth(ANCHO_BORDE)

    # Título
    ax.set_title(titulo, fontsize=12, fontweight="bold", pad= 20)

    # Texto debajo del título SOLO si se solicite
    if subtitulo:
        ax.text(0.5, 1.02, subtitulo, transform=ax.transAxes, ha="center",
                va="bottom", fontsize=9, color=COLOR_GRIS_LOGO)

    # Etiquetas
    ax.set_xlabel(xlabel, fontsize=10, fontweight="bold")
    ax.set_ylabel(ylabel, fontsize=10, fontweight="bold")

    # Ticks visibles en ambos ejes
    ax.tick_params(axis="x", which="both", bottom=True, top=False, labelrotation=rotacion_x,
                   length=4, width=1, direction="out")

    ax.tick_params(axis="y", which="both", left=True, right=False, labelrotation=0,
                   length=4, width=1, direction="out")

    # Agregar logo
    agregar_logo(plt.gcf(), RUTA_LOGO)

# =============
# CREAR GRÁFICO
# =============

def graficar(
        funcion,
        titulo,
        xlabel="",
        ylabel="",
        figsize=(8, 5),
        leyenda=False,
        rotacion_x=0,
        mostrar_valores=False,
        prefijo_valor="",
        subtitulo="",
        centrar_labels_x=False,
        **kwargs):
    """
    Crea cualquier gráfico de Seaborn.
    """
    plt.figure(figsize=figsize)
    ax = funcion(**kwargs)

    formato(
        ax,
        titulo,
        xlabel,
        ylabel,
        leyenda,
        rotacion_x,
        subtitulo
    )

    # Centrar labels SOLO cuando se solicite
    if centrar_labels_x:
        plt.setp(ax.get_xticklabels(), ha="right", va= "top")

    # Mostrar valores encima de las barras SOLO cuando se solicite
    if mostrar_valores:
        for contenedor in ax.containers:
            etiquetas = [
               f"{prefijo_valor}{valor.get_height():.0f}"
               for valor in contenedor
            ]
            ax.bar_label(
                contenedor,
                labels=etiquetas,
                padding=3,
                fontsize=12,
                fontweight="bold"
            )

        ax.margins(y=0.10)

    plt.show()

    # Agregar espacio entre gráficos
    display(HTML("<div style='height: 30px;'></div>"))

# =============================
# FUNCIÓN PRINCIPAL DE GRÁFICOS
# =============================

def funcion_graficos(df):

    orden_categoria, paleta_categoria = crear_paleta_categoria(df)
    orden_tipo, paleta_tipo = crear_paleta_tipo(df)

    # ==========================
    # Distribución de categorías
    # ==========================

    graficar(
        sns.countplot,
        "Distribución por categoría de eficiencia energética",
        "Categoría",
        "Cantidad",
        data=df,
        x="categoria",
        hue="categoria",
        order=orden_categoria,
        palette=paleta_categoria,
        edgecolor=COLOR_BORDE,
        linewidth=0.8,
        mostrar_valores=True,
        subtitulo= "De una muestra de 1000 datos"
    )

    # ============================
    # Costo promedio por categoría
    # ============================

    costo_categoria = (
        df.groupby("categoria")["costo_estimado"]
          .mean()
          .reset_index()
          .sort_values("costo_estimado")
    )

    graficar(
        sns.barplot,
        "Costo promedio por categoría de eficiencia energética",
        "Categoría",
        "Costo promedio ($)",
        data=costo_categoria,
        x="categoria",
        y="costo_estimado",
        hue="categoria",
        palette=paleta_categoria,
        edgecolor=COLOR_BORDE,
        linewidth=0.8,
        mostrar_valores=True,
        prefijo_valor="$"
    )

    # ==============================
    # Cantidad de equipos vs consumo
    # ==============================

    graficar(
        sns.scatterplot,
        "Relación entre cantidad de equipos y consumo",
        "Cantidad de equipos",
        "Consumo energético (kWh)",
        leyenda=True,
        data=df,
        x="cantidad_equipos",
        y="consumo_kwh",
        hue="categoria",
        palette=paleta_categoria
    )

    # ================================
    # Horas de alto consumo vs consumo
    # ================================

    graficar(
        sns.scatterplot,
        "Impacto de las horas de alto consumo",
        "Horas de alto consumo",
        "Consumo energético (kWh)",
        leyenda=True,
        data=df,
        x="horas_alto_consumo",
        y="consumo_kwh",
        hue="categoria",
        palette=paleta_categoria
    )

    # ===================================
    # Costo promedio por tipo de inmueble
    # ===================================

    costo_tipo = (
        df.groupby("tipo_inmueble")["costo_estimado"]
          .mean()
          .reset_index()
          .sort_values("costo_estimado")
    )

    graficar(
        sns.barplot,
        "Costo promedio por tipo de inmueble",
        "Tipo de inmueble",
        "Costo promedio ($)",
        data=costo_tipo,
        x="tipo_inmueble",
        y="costo_estimado",
        hue="tipo_inmueble",
        order=costo_tipo["tipo_inmueble"],
        hue_order=orden_tipo,
        palette=paleta_tipo,
        edgecolor=COLOR_BORDE,
        linewidth=0.8,
        mostrar_valores=True,
        prefijo_valor="$"
    )

    # ==============================
    # Tipo de inmueble por categoría
    # ==============================

    graficar(
        sns.countplot,
        "Tipo de inmueble por categoría de eficiencia energética",
        "Categoría de eficiencia energética",
        "Cantidad de inmuebles",
        leyenda=True,
        data=df,
        x="categoria",
        hue="tipo_inmueble",
        order=orden_categoria,
        hue_order=orden_tipo,
        palette=paleta_tipo,
        edgecolor=COLOR_BORDE,
        linewidth=0.8,
        mostrar_valores=True,
        subtitulo= "De una muestra de 1000 datos"
    )

    # ======================
    # Histograma del consumo
    # ======================

    graficar(
        sns.histplot,
        "Distribución del consumo energético",
        "Consumo energético (kWh)",
        "Cantidad de inmuebles",
        data=df,
        x="consumo_kwh",
        bins=30,
        kde=True,
        color=COLOR_HISTOGRAMA,
        subtitulo= "De una muestra de 1000 datos"
    )

    # ===========================================
    # Heatmap costo promedio por tipo y categoría
    # ===========================================

    tabla = (
        df.pivot_table(
            values="costo_estimado",
            index="tipo_inmueble",
            columns="categoria",
            aggfunc="mean"
        )
        .reindex(columns=["Eficiente", "Moderado", "Ineficiente"])
    )

    graficar(
        sns.heatmap,
        "Costo estimado promedio ($) por tipo de inmueble\n" "y categoría de eficiencia energética",
        figsize=(7, 4),
        data=tabla,
        annot=True,
        cmap=COLOR_CMAP_COSTO,
        fmt=".1f",
        linewidths=0.5,
        linecolor="white"
    )

    # =====================
    # Matriz de correlación
    # =====================

    variables_nombres = {
        "cantidad_personas": "Cantidad de personas",
        "cantidad_equipos": "Cantidad de equipos",
        "consumo_kwh": "Consumo energético",
        "costo_estimado": "Costo estimado",
        "horas_alto_consumo": "Horas de alto consumo"
    }

    correlacion = (
        df.select_dtypes(include=["int64", "float64"])
          .corr().rename(index= variables_nombres, columns= variables_nombres)
    )

    graficar(
        sns.heatmap,
        "Correlación entre variables",
        figsize=(8, 6),
        data=correlacion,
        annot=True,
        cmap=COLOR_CMAP_CORRELACION,
        fmt=".2f",
        linewidths=0.5,
        linecolor="white",
        rotacion_x=40,
        centrar_labels_x=True
    )

funcion_graficos(df)