spring.application.name=backend
spring.jackson.property-naming-strategy=SNAKE_CASE
oci.functions.endpoint=${OCI_FUNCTION_ENDPOINT:}
oci.functions.id=${OCI_FUNCTION_ID:}
python.api.url=http://127.0.0.1:8000
