spring.application.name=backend
spring.jackson.property-naming-strategy=SNAKE_CASE
oci.functions.endpoint=${OCI_FUNCTION_ENDPOINT:}
oci.functions.id=${OCI_FUNCTION_ID:}

spring.datasource.url=jdbc:h2:mem:energiai
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
